# Generated by Django 3.2 on 2021-12-24 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211223_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 1, 2, 59, 380066)),
        ),
        migrations.AlterField(
            model_name='sharepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 1, 2, 59, 381066)),
        ),
    ]
