# Generated by Django 3.2 on 2022-04-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpost',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_photos', to='posts.photo'),
        ),
    ]
