# Generated by Django 3.2 on 2022-04-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_savedpost_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpost',
            name='photo',
        ),
    ]
