# Generated by Django 4.0 on 2022-02-10 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_post_date_alter_sharepost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 0, 18, 25, 44157)),
        ),
        migrations.AlterField(
            model_name='sharepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 0, 18, 25, 44534)),
        ),
    ]
