# Generated by Django 3.2 on 2022-02-17 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220217_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 1, 21, 8, 300302)),
        ),
        migrations.AlterField(
            model_name='sharepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 1, 21, 8, 300643)),
        ),
    ]
