# Generated by Django 3.2 on 2021-12-24 05:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0005_alter_follow_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followee_id',
            new_name='followee',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.AlterField(
            model_name='follow',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 5, 23, 40, 77643, tzinfo=utc)),
        ),
    ]
