# Generated by Django 3.2 on 2021-12-24 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0007_auto_20211223_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 7, 2, 59, 378066, tzinfo=utc)),
        ),
    ]
