# Generated by Django 4.0 on 2022-02-10 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0013_alter_follow_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 0, 18, 25, 38514, tzinfo=utc)),
        ),
    ]
