# Generated by Django 3.2 on 2022-02-17 01:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0015_alter_follow_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 1, 19, 55, 908068, tzinfo=utc)),
        ),
    ]
