# Generated by Django 3.2 on 2022-02-17 01:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0016_alter_follow_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 1, 21, 8, 295409, tzinfo=utc)),
        ),
    ]
